name: tensorflow_gpu
channels:
  - conda-forge
  - pytorch
  - fastai
  - defaults
dependencies:
  - python=3.6
  - tensorflow-gpu=1.10
  - cuda92
  - jupyter
  - pillow
  - requests
  - pip:
      - nvidia-ml-py3
